<template lang="pug">
.tooltip
    p.date {{ date }}
    p.orders {{ $t("dashboard.orders.Orders") }}: {{ numberOfOrders }}
</template>
<script setup lang="ts">

defineProps<{
    date: string,
    numberOfOrders: number,
}>();

</script>
<style scoped lang="scss">
.tooltip {
    font-family: $font-stack; // needed to override the font-family of the parent container generated by chart library

    @include normal-text;
    color: $color-text-lighter;

    .date {
        @include normal-medium-text;
        color: $color-text-normal;

        margin-bottom: steps(0.5);
    }
}
</style>
