export enum WaitingFor {
    OrderRows = "order-rows",
    OrderListColumns = "order-list-columns",
    OrderListAction = "order-list-action",
    OrdersCalendarOrders = "orders-calendar-orders",
    OrdersCalendarBlockedTimeReasons = "orders-calendar-blocked-time-reasons",
    OrdersCalendarBlockedTimePeriods = "orders-calendar-blocked-time-periods",
    OrdersCalendarBlockedTimePeriodCreation = "orders-calendar-blocked-time-period-creation",
    OrdersCalendarBlockedTimePeriodRemoval = "orders-calendar-blocked-time-period-removal",
    OrderFormOrderLoading = "order-form-order-loading",
    OrderFormOrderSaving = "order-form-order-saving",
    OrderFormOrderRecalculation = "order-form-order-recalculation",
    OrderFormOrderAutoPlanning = "order-form-order-auto-planning",
    OrderFormCustomers = "order-form-customers",
    OrderFormContacts = "order-form-contacts",
    OrderFormProjects = "order-form-projects",
    OrderFormAgreements = "order-form-agreements",
    OrderFormOperations = "order-form-operations",
    OrderFormServices = "order-form-services",
    OrderFormCargoTypes = "order-form-cargo-types",
    OrderFormWaybillNumber = "order-form-waybill-number",
    OrderFormDestinations = "order-form-destinations",
    OrderFormDestinationSaving = "order-form-destination-saving",
    OrderFormLines = "order-form-lines",
    OrderFormTransportOrderStages = "order-form-transport-order-stages",
    OrderFormActivities = "order-form-activities",
    OrderFormSpecificationRowQuantityTypes = "order-form-specification-row-quantity-types",
    OrderFormArticleGroups = "order-form-article-groups",
    OrderFormArticles = "order-form-articles",
    OrderFormQuantityUnits = "order-form-quantity-units",
    OrderFormGoodsRowQuantityTypes = "order-form-goods-row-quantity-types",
    OrderFormDangerousGoodsRowQuantityTypes = "order-form-dangerous-goods-row-quantity-types",
    OrderFormDangerousGoodsRowSubstanceTypes = "order-form-dangerous-goods-row-substance-types",
    OrderFormUnitedNationsNumbers = "order-form-united-nations-numbers",
    OrderFormWasteCodes = "order-form-waste-codes",
    OrderFormDocumentTypes = "order-form-document-types",
    OrderFormDeviationTypes = "order-form-deviation-types",
    OrderFormAuditEntries = "order-form-audit-entries",
    OrderFormPayees = "order-form-payees",
    Routes = "routes",
    RouteFormRouteLoading = "route-form-route-loading",
    RouteFormRouteSaving = "route-form-route-saving",
    RouteDrivingTimeCalculation = "route-driving-time-calculation",
    RouteDialogAction = "route-dialog-action",
    OrderTemplates = "order-templates",
    Search = "search",
    SearchResults = "search-results",

    Views = "views",
    ViewSaveAsNew = "view-save-as-new",
    ViewSave = "view-save",
    ViewDelete = "view-delete",
    ViewRevert = "view-revert",
    ViewUpsert = "view-upsert",

    Units = "units",

    TransportOrderLoading = "transport-order-loading",
    TransportOrderDispatching = "transport-order-dispatching",
    TransportOrderCompleting = "transport-order-completing",
    OrderDeleting = "order-deleting",
    AddingToRoute = "adding-to-route",

    OrderActions = "order-actions",

    InvoicingOrderRows = "invoicing-order-rows",
    InvoicingOrderColumns = "invoicing-order-columns",
    MarkingOrdersAsInvoiceable = "marking-orders-as-invoiceable",
    InvoicingProcessCreation = "invoicing-process-creation",
    InvoicingProfiles = "invoicing-profiles",
    InvoicingProcesses = "invoicing-processes",
    InvoicingProcessLoading = "invoicing-process-loading",
    InvoicingProcessCancelling = "invoicing-process-cancelling",
    InvoicingProcessRestarting = "invoicing-process-restarting",
    InvoicingProcessMarkingExternalProcessingAsDone = "invoicing-process-marking-external-processing-as-done",

    SelfBillingOrderRows = "self-billing-order-rows",
    SelfBillingOrderColumns = "self-billing-order-columns",

    FileUpload = "file-upload",
}
