export const INVOICING_ORDER_ROW_DEFINITION = buildTableColumnDefinition({
    number: "string",
    customer_name: "string",
    operation_name: "string",
    status: {
        type: "enum",
        enum: OrderStatus,
        translationScope: "order.statuses"
    },
    invoice_group: "string",
    invoice_number: "string",
    created_at: {
        type: "date",
        filterOn: "created_at_date",
    },
    updated_at: {
        type: "date",
        filterOn: "updated_at_date",
    },
    amount: {
        type: "number",
        numberFormat: "currency",
    },
    waybill_number: "string",
    customer_reference: "string",
    customer_short_name: "string",
    customer_number: "string",
    customer_contact: "string",
    subcustomer: "string",
    unit_names: "string",
    unit_numbers: "string",
    service_name: "string",
    registered_by: "string",
    registered_at: {
        type: "date",
        filterOn: "registered_at_date",
    },
    planned_at: {
        type: "date",
        filterOn: "planned_at_date",
    },
    delivered_at: {
        type: "date",
        filterOn: "delivered_at_date",
    },
    unit_total: {
        type: "number",
        numberFormat: "currency",
    },
    customer_total:{
        type: "number",
        numberFormat: "currency",
    },
    invoice_text: "string",
    invoice_profile: "string",
    invoice_type: "string",
    invoice_process_status: {
        type: "enum",
        enum: InvoicingProcessStatus,
        translationScope: "invoicing.processes.statuses"
    },
} as const);


// Base columns (mostly ids) which are never shown to the user
// thus not needed to have definitions
type InvoicingOrderRowBaseColumns = {
    id: string,
};

// columns that are generated by frontend
type InvoicingOrderRowGeneratedColumns = {
    created_at_date: string | null,
    created_at_time: string | null,

    updated_at_date: string | null,
    updated_at_time: string | null,

    registered_at_date: string | null,
    registered_at_time: string | null,

    planned_at_date: string | null,
    planned_at_time: string | null,

    delivered_at_date: string | null,
    delivered_at_time: string | null,
};


type InvoicingOrderRowDefinedColumns = InferRowType<typeof INVOICING_ORDER_ROW_DEFINITION>;

export type InvoicingOrderRow = InvoicingOrderRowBaseColumns & InvoicingOrderRowDefinedColumns & InvoicingOrderRowGeneratedColumns;
export type InvoicingOrderRowKey = keyof InvoicingOrderRow;
export type DefinedInvoiceableOrderRowKey = keyof InvoicingOrderRowDefinedColumns;
