export const SELF_BILLING_ORDER_ROW_DEFINITION = buildTableColumnDefinition({
    group: "string",
    profile: "string",
    status: "string",
    number: "string",
    order_number: "string",
    waybill: "string",
    unit_number: "string",
    unit_total: {
        type: "number",
        decimals: 2,
    },
    vehicle_name: "string",
    carrier_name: "string",
    carrier_short_name: "string",
    service_name: "string",
    operation_name: "string",
    customer_name: "string",
    customer_short_name: "string",
    customer_number: "string",
    customer_reference: "string",
    customer_contact: "string",
    subcustomer_name: "string",
    registered_at: {
        type: "date",
        filterOn: "registered_at_date",
        sortDateOn: "registered_at_date",
        sortTimeOn: "registered_at_time"
    },
    registered_by: "string",
    planned_at: {
        type: "date",
        filterOn: "planned_at_date",
        sortDateOn: "planned_at_date",
        sortTimeOn: "planned_at_time"
    },
    dispatched_at: {
        type: "date",
        filterOn: "dispatched_at_date",
        sortDateOn: "dispatched_at_date",
        sortTimeOn: "dispatched_at_time"
    },
    accepted_at: {
        type: "date",
        filterOn: "accepted_at_date",
        sortDateOn: "accepted_at_date",
        sortTimeOn: "accepted_at_time"
    },
    started_at: {
        type: "date",
        filterOn: "started_at_date",
        sortDateOn: "started_at_date",
        sortTimeOn: "started_at_time"
    },
    completed_at: {
        type: "date",
        filterOn: "completed_at_date",
        sortDateOn: "completed_at_date",
        sortTimeOn: "completed_at_time"
    },
    verified_at: {
        type: "date",
        filterOn: "verified_at_date",
        sortDateOn: "verified_at_date",
        sortTimeOn: "verified_at_time"
    },
    planned_pickup_at: {
        type: "date",
        filterOn: "planned_pickup_at_date",
        sortDateOn: "planned_pickup_at_date",
        sortTimeOn: "planned_pickup_at_time"
    },
    planned_delivery_at: {
        type: "date",
        filterOn: "planned_delivery_at_date",
        sortDateOn: "planned_delivery_at_date",
        sortTimeOn: "planned_delivery_at_time"
    },
    payees: "string",
    created_at: {
        type: "date",
        filterOn: "created_at_date",
        sortDateOn: "created_at_date",
        sortTimeOn: "created_at_time"
    },
    updated_at: {
        type: "date",
        filterOn: "updated_at_date",
        sortDateOn: "updated_at_date",
        sortTimeOn: "updated_at_time"
    },
} as const);



// Base columns (mostly ids) which are never shown to the user
// thus not needed to have definitions
type SelfBillingOrderRowBaseColumns = {
    id: string,
};

// columns that are generated by frontend or backend
type SelfBillingOrderRowGeneratedColumns = {
    created_at_utc: string | null,
    updated_at_utc: string | null,

    //
    // generated fields by backend that contains
    // separated date and time for the dates, used by orderlist
    // to handle sort and filtering.
    registered_at_date: string | null,
    registered_at_time: string | null,

    planned_at_date: string | null,
    planned_at_time: string | null,

    dispatched_at_date: string | null,
    dispatched_at_time: string | null,

    accepted_at_date: string | null,
    accepted_at_time: string | null,

    started_at_date: string | null,
    started_at_time: string | null,

    completed_at_date: string | null,
    completed_at_time: string | null,

    verified_at_date: string | null,
    verified_at_time: string | null,

    planned_pickup_at_date: string | null,
    planned_pickup_at_time: string | null,

    planned_delivery_at_date: string | null,
    planned_delivery_at_time: string | null,

    created_at_date: string | null,
    created_at_time: string | null,

    updated_at_date: string | null,
    updated_at_time: string | null,
};


type SelfBillingOrderRowDefinedColumns = InferRowType<typeof SELF_BILLING_ORDER_ROW_DEFINITION>;

export type SelfBillingOrderRow = SelfBillingOrderRowBaseColumns & SelfBillingOrderRowDefinedColumns & SelfBillingOrderRowGeneratedColumns;
export type SelfBillingOrderRowKey = keyof SelfBillingOrderRow;
export type DefinedSelfBillingOrderRowKey = keyof SelfBillingOrderRowDefinedColumns;

